### ISSUE TITLE
Can not zoom

### ISSUE THREAD

**Issue by Honghe** [Lorti/webgl-3d-model-viewer-using-three.js#1]
It says `//    Zoom - middle mouse, or mousewheel / touch: two finger spread or squish`
But can not zoom via mouse or touch.
`OrbitControls.js` setting:
```
// This option actually enables dollying in and out; left as "zoom" for backwards compatibility.
// Set to false to disable zooming
this.enableZoom = true;
this.zoomSpeed = 1.0;
```
Thanks!

**Comment by Lorti** [comment]
Is your question related to your code or is it related to my example? Please don't open an issue if it is not related to my example. You should rather ask me via Disqus on [WebGL 3D Model Viewer Using three.js](https://manu.ninja/webgl-3d-model-viewer-using-three-js) so others may also benefit from the answer.

I have disabled zooming in my example, you can enable it by removing the following [line 146]
(https://github.com/Lorti/webgl-3d-model-viewer-using-three.js/blob/master/index.html#L146).

**Comment by Honghe** [comment]
@Lorti I miss the setting on the `index.html` file. Thanks!
